# -*- perl -*-
# DO NOT EDIT - This file is generated by UMMF; http://ummf.sourceforge.net 
# From template: $Id: PerlTemplate.txt,v 1.74 2004/08/01 03:50:07 kstephens Exp $

package UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState;

#use 5.6.1;
use strict;
use warnings;

#################################################################
# Version
#

our $VERSION = do { my @r = (q{1.0} =~ /\d+/g); sprintf "%d." . "%03d" x $#r, @r };


#################################################################
# Documentation
#

=head1 NAME

UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState -- 

=head1 VERSION

1.0

=head1 SYNOPSIS

=head1 DESCRIPTION 

=head1 USAGE

=head1 EXPORT

=head1 METATYPE

L<UMMF::UML::MetaModel::Foundation::Core::Class|UMMF::UML::MetaModel::Foundation::Core::Class>

=head1 SUPERCLASSES

L<UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState|UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState>




=head1 ATTRIBUTES


=head2 C<isDynanmic> : UMMF::UML::MetaModel::Foundation::Data_Types::Boolean 


=over 4

=item metatype = L<UMMF::UML::MetaModel::Foundation::Core::Attribute|UMMF::UML::MetaModel::Foundation::Core::Attribute>

=item type = L<UMMF::UML::MetaModel::Foundation::Data_Types::Boolean|UMMF::UML::MetaModel::Foundation::Data_Types::Boolean>

=item visibility = C<private>

=item multiplicity = C<1>

=item changeability = C<changeable>

=item targetScope = C<instance>

=item ordering = C<unordered>

=item initialValue = I<UNSPECIFIED>

=item container_type = C<Set::Object>

=back


=head2 C<dyanmicArguments> : UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression 


=over 4

=item metatype = L<UMMF::UML::MetaModel::Foundation::Core::Attribute|UMMF::UML::MetaModel::Foundation::Core::Attribute>

=item type = L<UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression|UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression>

=item visibility = C<private>

=item multiplicity = C<1>

=item changeability = C<changeable>

=item targetScope = C<instance>

=item ordering = C<unordered>

=item initialValue = I<UNSPECIFIED>

=item container_type = C<Set::Object>

=back


=head2 C<dynamicMultiplicity> : UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity 


=over 4

=item metatype = L<UMMF::UML::MetaModel::Foundation::Core::Attribute|UMMF::UML::MetaModel::Foundation::Core::Attribute>

=item type = L<UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity|UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity>

=item visibility = C<private>

=item multiplicity = C<1>

=item changeability = C<changeable>

=item targetScope = C<instance>

=item ordering = C<unordered>

=item initialValue = I<UNSPECIFIED>

=item container_type = C<Set::Object>

=back



=head1 ASSOCIATIONS

I<NO ASSOCIATIONS>


=head1 METHODS

=cut



#################################################################
# Dependencies
#





use Carp qw(croak confess);
use Set::Object 1.05;
use Class::Multimethods 1.70;
use Data::Dumper;
use Scalar::Util qw(weaken);
use UMMF::UML::MetaModel::__ObjectBase qw(:__ummf_array);


#################################################################
# Generalizations
#

use base qw(
  UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState



);


#################################################################
# Exports
#

our @EXPORT_OK = qw(
);
our %EXPORT_TAGS = ( 'all' => \@EXPORT_OK );





#################################################################
# Validation
#


=head2 C<__validate_type>

  UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState->__validate_type($value);

Returns true if C<$value> is a valid representation of L<UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState|UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState>.

=cut
sub __validate_type($$)
{
  my ($self, $x) = @_;

  no warnings;

  UNIVERSAL::isa($x, 'UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState')  ;
}


=head2 C<__typecheck>

  UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState->__typecheck($value, $msg);

Calls C<confess()> with C<$msg> if C<<UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState->__validate_type($value)>> is false.

=cut
sub __typecheck
{
  my ($self, $x, $msg) = @_;

  confess("typecheck: $msg: type '" . 'UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState' . ": value '$x'")
    unless __validate_type($self, $x);
}


=head2 C<isaSubactivityState>


Returns true if receiver is a L<UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState|UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState>.
Other receivers will return false.

=cut
sub isaSubactivityState { 1 }


=head2 C<isaBehavioral_Elements__Activity_Graphs__SubactivityState>


Returns true if receiver is a L<UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState|UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState>.
Other receivers will return false.
This is the fully qualified version of the C<isaSubactivityState> method.

=cut
sub isaBehavioral_Elements__Activity_Graphs__SubactivityState { 1 }


#################################################################
# Introspection
#

=head2 C<__model_name> 

  my $name = $obj_or_package->__model_name;

Returns the UML Model name (C<'Behavioral_Elements::Activity_Graphs::SubactivityState'>) for an object or package of
this Classifier.

=cut
sub __model_name { 'Behavioral_Elements::Activity_Graphs::SubactivityState' }



=head2 C<__isAbstract>

  $package->__isAbstract;

Returns C<0>.

=cut
sub __isAbstract { 0; }


my $__tangram_schema;
=head2 C<__tangram_schema>

  my $tangram_schema $obj_or_package->__tangram_schema

Returns a HASH ref that describes this Classifier for Tangram.

See L<UMMF::UML::Export::Perl::Tangram|UMMF::UML::Export::Perl::Tangram>

=cut
sub __tangram_schema
{
  my ($self) = @_;

  $__tangram_schema ||=
  {
   'classes' =>
   [
     'UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState' =>
     {
       'table' => 'Behavioral_Elements__Activity_Graphs__SubactivityState',
       'abstract' => 0,
       'slots' => 
       { 
	 # Attributes
	 	       'isDynanmic'
       => {
	 'type_impl' => 'string',
                                             'col' => 'isDynanmic', 

                                                                                                                   }
      ,
         	       'dyanmicArguments'
       => {
	 'type_impl' => 'ref',
         'class' => 'UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression',

                                             'col' => 'dyanmicArguments', 

                                                                                                                   }
      ,
         	       'dynamicMultiplicity'
       => {
	 'type_impl' => 'ref',
         'class' => 'UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity',

                                             'col' => 'dynamicMultiplicity', 

                                                                                                                   }
      ,
         
	 # Associations
	        },
       'bases' => [  'UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState',  ],
       'sql' => {

       },
     },
   ],

   'sql' =>
   {
    # Note Tangram::Ref::get_exporter() has
    # "UPDATE $table SET $self->{col} = $refid WHERE id = $id",
    # The id_col is hard-coded, 
    # Thus id_col will not work.
    #'id_col' => '__sid',
    #'class_col' => '__stype',
   },
     # 'set_id' => sub { }
     # 'get_id' => sub { }

      
  };
}


#################################################################
# Class Attributes
#


          

#################################################################
# Class Associations
#


    

#################################################################
# Initialization
#


=head2 C<___initialize>

Initialize all Attributes and AssociationEnds in a instance of this Classifier.
Does B<not> initalize slots in its Generalizations.

See also: C<__initialize>.

=cut
sub ___initialize
{
  my ($self) = @_;

  # Attributes

    # Attribute isDynanmic
  if ( exists $self->{'isDynanmic'} ) {
    my $x = $self->{'isDynanmic'};
    $self->{'isDynanmic'} = undef;
    $self->set_isDynanmic($x);
  } else {
      }
  
    # Attribute dyanmicArguments
  if ( exists $self->{'dyanmicArguments'} ) {
    my $x = $self->{'dyanmicArguments'};
    $self->{'dyanmicArguments'} = undef;
    $self->set_dyanmicArguments($x);
  } else {
      }
  
    # Attribute dynamicMultiplicity
  if ( exists $self->{'dynamicMultiplicity'} ) {
    my $x = $self->{'dynamicMultiplicity'};
    $self->{'dynamicMultiplicity'} = undef;
    $self->set_dynamicMultiplicity($x);
  } else {
      }
  


  # Associations


  $self;
}


my $__initialize_use;

=head2 C<__initialize>

Initialize all slots in this Classifier and all its Generalizations.

See also: C<___initialize>.

=cut
sub __initialize
{
  my ($self) = @_;

  # $DB::single = 1;

  unless ( ! $__initialize_use ) {
    $__initialize_use = 1;
    $self->__use('UMMF::UML::MetaModel::Foundation::Core::Element');
    $self->__use('UMMF::UML::MetaModel::Foundation::Core::ModelElement');
    $self->__use('UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::StateVertex');
    $self->__use('UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::State');
    $self->__use('UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::CompositeState');
    $self->__use('UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState');
  }

  $self->UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState::___initialize;
  $self->UMMF::UML::MetaModel::Foundation::Core::Element::___initialize;
  $self->UMMF::UML::MetaModel::Foundation::Core::ModelElement::___initialize;
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::StateVertex::___initialize;
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::State::___initialize;
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::CompositeState::___initialize;
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState::___initialize;

  $self;
}
      

=head2 C<__create>

Calls all <<create>> Methods for this Classifier and all Generalizations.

See also: C<___create>.

=cut
sub __create
{
  my ($self, @args) = @_;

  # $DB::single = 1;
  $self->UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState::___create(@args);
  $self->UMMF::UML::MetaModel::Foundation::Core::Element::___create();
  $self->UMMF::UML::MetaModel::Foundation::Core::ModelElement::___create();
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::StateVertex::___create();
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::State::___create();
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::CompositeState::___create();
  $self->UMMF::UML::MetaModel::Behavioral_Elements::State_Machines::SubmachineState::___create();

  $self;
}




#################################################################
# Attributes
#



=for html <hr/>

=cut

#################################################################
# Attribute isDynanmic
# type = UMMF::UML::MetaModel::Foundation::Data_Types::Boolean
# multiplicity = 1
# ordering = unordered
# ownerScope = instance
# initialValue = 

=head2 C<isDynanmic>

  my $val = $obj->isDynanmic;

Returns the L<UMMF::UML::MetaModel::Foundation::Data_Types::Boolean|UMMF::UML::MetaModel::Foundation::Data_Types::Boolean> value of Attribute C<isDynanmic>.

=cut
sub isDynanmic ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'isDynanmic'};

  ;

  $val;
}


=head2 C<set_isDynanmic>

  $obj->set_isDynanmic($val);

Sets the value of Attribute C<isDynanmic>.
C<$val> must be of type L<UMMF::UML::MetaModel::Foundation::Data_Types::Boolean|UMMF::UML::MetaModel::Foundation::Data_Types::Boolean> or C<undef>.
Returns C<$obj>.

=cut
sub set_isDynanmic ($$)
{
  my ($self, $val) = @_;

  ;

  if ( defined $val ) {
    ;
  }

    $self->{'isDynanmic'} = $val
  ;

  ;

  $self;
}


=head2 C<count_isDynanmic>

  $obj->count_isDynanmic;

Returns the number of elements (0 or 1) in C<isDynanmic>.

=cut
sub count_isDynanmic ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'isDynanmic'};

  ;

  defined $val ? 1 : 0;
}



=for html <hr/>

=cut

#################################################################
# Attribute dyanmicArguments
# type = UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression
# multiplicity = 1
# ordering = unordered
# ownerScope = instance
# initialValue = 

=head2 C<dyanmicArguments>

  my $val = $obj->dyanmicArguments;

Returns the L<UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression|UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression> value of Attribute C<dyanmicArguments>.

=cut
sub dyanmicArguments ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'dyanmicArguments'};

  ;

  $val;
}


=head2 C<set_dyanmicArguments>

  $obj->set_dyanmicArguments($val);

Sets the value of Attribute C<dyanmicArguments>.
C<$val> must be of type L<UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression|UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression> or C<undef>.
Returns C<$obj>.

=cut
sub set_dyanmicArguments ($$)
{
  my ($self, $val) = @_;

  ;

  if ( defined $val ) {
    $self->__use('UMMF::UML::MetaModel::Foundation::Data_Types::ArgListExpression')->__typecheck($val, "UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState.dyanmicArguments");
  }

    $self->{'dyanmicArguments'} = $val
  ;

  ;

  $self;
}


=head2 C<count_dyanmicArguments>

  $obj->count_dyanmicArguments;

Returns the number of elements (0 or 1) in C<dyanmicArguments>.

=cut
sub count_dyanmicArguments ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'dyanmicArguments'};

  ;

  defined $val ? 1 : 0;
}



=for html <hr/>

=cut

#################################################################
# Attribute dynamicMultiplicity
# type = UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity
# multiplicity = 1
# ordering = unordered
# ownerScope = instance
# initialValue = 

=head2 C<dynamicMultiplicity>

  my $val = $obj->dynamicMultiplicity;

Returns the L<UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity|UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity> value of Attribute C<dynamicMultiplicity>.

=cut
sub dynamicMultiplicity ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'dynamicMultiplicity'};

  ;

  $val;
}


=head2 C<set_dynamicMultiplicity>

  $obj->set_dynamicMultiplicity($val);

Sets the value of Attribute C<dynamicMultiplicity>.
C<$val> must be of type L<UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity|UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity> or C<undef>.
Returns C<$obj>.

=cut
sub set_dynamicMultiplicity ($$)
{
  my ($self, $val) = @_;

  ;

  if ( defined $val ) {
    $self->__use('UMMF::UML::MetaModel::Foundation::Data_Types::Multiplicity')->__typecheck($val, "UMMF::UML::MetaModel::Behavioral_Elements::Activity_Graphs::SubactivityState.dynamicMultiplicity");
  }

    $self->{'dynamicMultiplicity'} = $val
  ;

  ;

  $self;
}


=head2 C<count_dynamicMultiplicity>

  $obj->count_dynamicMultiplicity;

Returns the number of elements (0 or 1) in C<dynamicMultiplicity>.

=cut
sub count_dynamicMultiplicity ($)
{
  my ($self) = @_;

  ;

  my $val = $self->{'dynamicMultiplicity'};

  ;

  defined $val ? 1 : 0;
}




#################################################################
# Association
#





# End of Class SubactivityState


=pod

=for html <hr/>

I<END OF DOCUMENT>

=cut

############################################################################

1; # is true!

############################################################################

### Keep these comments at end of file: kstephens@users.sourceforge.net 2003/04/06 ###
### Local Variables: ###
### mode:perl ###
### perl-indent-level:2 ###
### perl-continued-statement-offset:0 ###
### perl-brace-offset:0 ###
### perl-label-offset:0 ###
### End: ###

